name: frontend_waste_management_stackholder
description: "Laraan For stackholder"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_dotenv: ^5.0.2
  http: ^1.2.1
  golden_toolkit: ^0.15.0
  permission_handler: ^11.3.1
  geolocator: ^11.1.0
  geocoding: ^3.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  flutter_map_location_marker: ^8.1.0
  flutter_map_supercluster: ^5.0.0-dev.1
  flutter_map_heatmap: ^0.0.7
  flutter_map_compass: ^1.0.3
  flutter_launcher_icons: ^0.13.1
  flutter_map_cancellable_tile_provider: ^2.0.0
  overlay_kit: ^1.0.8
  jwt_decoder: ^2.0.1
  connectivity_plus: ^4.0.2
  fl_chart: ^0.69.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/data/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/poppins/Poppins-Regular.ttf
        - asset: assets/font/poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/font/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/font/poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/font/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/font/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font/poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/font/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/font/poppins/Poppins-BoldItalic.ttf
          style: italic
          weight: 700
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"
